### ISSUE TITLE
GitHub pages for website

### ISSUE THREAD

**Issue by giacomocerquone** [KurtisLiggett/Simple-IP-Config#10]
I see you're creating a website in the docs folder. I'd use jekyll with gh-pages. Some info for you here https://pages.github.com/

**Comment by KurtisLiggett** [comment]
What are some of the advantages of using gh-pages vs the /docs folder?
Keeping the website separate from master? I see how this could be easier to maintain with several contributors.
As I'm still testing, I'm open to rearranging things..

I did finally get Jekyll set up on my PC, so I won't be continuously committing/pushing to test changes anymore.

**Comment by giacomocerquone** [comment]
Point is that I'm not understanding how I should access the website inside the docs folder.
Using gh-pages would for sure separate the website and the application and plus you'll get a free third level domain (or use a second one if you have it) to show your project

**Comment by KurtisLiggett** [comment]
The docs folder behaves the same as gh-pages; I just thought it would be easier to get started. The address is the same.
[https://kurtisliggett.github.io/Simple-IP-Config](https://kurtisliggett.github.io/Simple-IP-Config)

**Comment by giacomocerquone** [comment]
Well then, being a web developer if you need something there I can easily help you :)

**Comment by KurtisLiggett** [comment]
I think I will move the website to the gh-pages branch to keep the master branch tidy.
