### ISSUE TITLE
One Network Adapter per User (RDS Scenario)

### ISSUE THREAD

**Issue by lixaotec** [KurtisLiggett/Simple-IP-Config#100]
Dear folks, 

I know that this might not be the best place to ask this question, however I don´t know anywhere else to get another approach, and I hope someone here has a deep knowldge on this challenge;

I´m trying to estabilsh one IP per User in a Windows Server 2019 env with RDS. There´s a feature RDS IP Virtualization, that MS says its broken on WS2019.

I found this tool, and was wondering if somebody knows a workaround to achieve that, with or without this tool? I though to create several network adapter, however I dont know if its possible to assign each for each user?

Appreacite any help.

Thanks in adv,

**Comment by KurtisLiggett** [comment]
I'm not sure how this works, but I don't think this is the solution.
