### ISSUE TITLE
[BUG] COM Error 80020009

### ISSUE THREAD

**Issue by bumpy703** [KurtisLiggett/Simple-IP-Config#103]
**Version:**
What version are you using?
**2.9.3**

**Expected Behavior:**
A clear description of what you expected to happen.
**Open the program, launch like normal.**

**Actual Behavior:**
A clear description of what _actually_ happened.
**While connected to the internet, the program launches normally. While disconnectd from the internet, error pops up before I can use the program**

Also, is it possible to have it so that while the program is already running, when you click the icon on desktop or taskbar to bring the window to the foreground instead of a popup that says "program is already running"?

**Comment by KurtisLiggett** [comment]
Bug confirmed. Split feature request (bring to foreground) to better track the issues.

**Comment by KurtisLiggett** [comment]
Bug should be fixed and will be included in the next release.
