### ISSUE TITLE
[FEATURES] Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [KurtisLiggett/Simple-IP-Config#128]
**Version:**
2.9.3

**Expected Behavior:**
Please enable multilanguage GUI

**Actual Behavior:**
Your program use Autoit.
Please using Autoit modify the source to use an external langauge file to translate as much as you can the GUI strings.

**Comment by KurtisLiggett** [comment]
I would like to keep Issues limited to bug reports.
Feature requests should now go in the Discussions area under the Ideas category. There is already an open discussion on multilanguage GUI. #117
