### ISSUE TITLE
Multilanguage installer

### ISSUE THREAD

**Issue by bovirus** [KurtisLiggett/Simple-IP-Config#129]
@KurtisLiggett 

This the new Inno Setup installer script multilanguage (English + Italian).
Tested in my configuration.

[Simple-IP-Config-Setup.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8440706/Simple-IP-Config-Setup.zip)

Please merge it.

**Comment by KurtisLiggett** [comment]
Updated

**Comment by blackcrack** [comment]
don't forget to hold an easy decompression for a portable Possibility  .... and a silence switch /q with a progress window(to see what's goes on) /s or /silence, /unattended and so on.. 
best

m. 2$

**Comment by bovirus** [comment]
@KurtisLiggett 

Improvement of instalelr script

[Simple-IP-Config-Setup-R02.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8449647/Simple-IP-Config-Setup-R02.zip)

- Changes
Added reference to language files (.json files)
Added Russian language to the installer

**Comment by KurtisLiggett** [comment]
Thanks for the help. I actually have a script prepared for the languages, but I'm saving it for when language files are officially supported and the bugs are worked out. I like some of your additions, so I combined them here.

[Simple-IP-Config-Setup-03.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8452007/Simple-IP-Config-Setup-03.zip)

* User can select whether or not to install language files and which ones.

**Comment by bovirus** [comment]
@KurtisLiggett 

In my point of view is better to install all language files anyway.
In this case you can switch to anew language without a new installatiuon.
The langaueg file are quite smaller and you din't save so many free space.

**Comment by mrkaban** [comment]
russian.InstallationFull=Полная установка
russian.InstallationCompact=Компактная установка
russian.InstallationCustom=Выборочная установка
russian.ProgramFiles=Program Files
russian.AdditionalLanguageFiles=Дополнительные языковые файлы (английский включен по умолчанию)
russian.LanguageItalian=Итальянский
russian.LanguageRussian=Русский

Is there anything else that needs to be translated?

**Comment by bovirus** [comment]
@KurtisLiggett 

New Inno Setup Script with strings in Russian

[Simple-IP-Config-Setup-R05.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8454141/Simple-IP-Config-Setup-R05.zip)

**Comment by KurtisLiggett** [comment]
languages added to installer in release v2.9.4. Closing for now.
