### ISSUE TITLE
Spanish Translate

### ISSUE THREAD

**Issue by andago9** [KurtisLiggett/Simple-IP-Config#135]
Hi, If you need help with the Spanish translation, let me know.

**Comment by KurtisLiggett** [comment]
If you could go to this page #132 and post the translation file there, that would be super helpful!

**Comment by andago9** [comment]
Hi, the link doesn't work. It throws me the 404 error, 

https://github.com/KurtisLiggett/Simple-IP-Config/blob/assets/language%20files/lang-en-US.json

**Comment by KurtisLiggett** [comment]
@andago9 
Sorry about that, links should be fixed now.
[download lang-en-US.json](https://github.com/KurtisLiggett/Simple-IP-Config/blob/master/lang/lang-en-US.json)

**Comment by andago9** [comment]
Hello, I upload it with a .txt extension

let me know when a new release is available to check that it is ok, and too future changes
[lang-es-ES.txt](https://github.com/KurtisLiggett/Simple-IP-Config/files/8509448/lang-es-ES.txt)

**Comment by KurtisLiggett** [comment]
New release v2.9.4 now includes spanish translation
