### ISSUE TITLE
Tabbing out of new profile name causes crash

### ISSUE THREAD

**Issue by bruingineer** [KurtisLiggett/Simple-IP-Config#143]
this affects 2.9.2 and 2.9.3 at least.

**Comment by bruingineer** [comment]
Seems to happen when there are no profiles and when creating the first profile

**Comment by KurtisLiggett** [comment]
Confirmed here. I have fixed some related issues with creating the first  profile, but I haven't seen this one is new to me.
@bruingineer For me, the app stops responding then just closes with no error message. Is that what you are seeing?

Thanks for reporting, I really appreciate it.

**Comment by bruingineer** [comment]
yes, app freezes then closes

**Comment by KurtisLiggett** [comment]
That was a tricky one to figure out! Should be fixed in the next release. Or you can try out the lastest (unreleased) version, if you're interested. [Simple-IP-Config-2_9_4-BETA07.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8682823/Simple-IP-Config-2_9_4-BETA07.zip)

**Comment by bruingineer** [comment]
Cool I will try it tonight. I've some other weird quirks with typing in the address fields. I'll make a separate issue for those.

**Comment by bruingineer** [comment]
now when I tab away, the new profile goes away. 

I would expect it to keep whatever name is typed in and move the cursor focus to the next IP text field

**Comment by KurtisLiggett** [comment]
I guess I figured people would press ENTER to save the name and escape or tab to cancel, but I'm good with your suggestion. Something like this?
[Simple-IP-Config-2_9_4-BETA08.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8692048/Simple-IP-Config-2_9_4-BETA08.zip)

**Comment by KurtisLiggett** [comment]
v2.9.4 released to fix this issue.
