### ISSUE TITLE
Automatic Update

### ISSUE THREAD

**Issue by JBSoft** [KurtisLiggett/Simple-IP-Config#15]
Would it be possible to add an update feature to this great app ?

Thanks

**Comment by KurtisLiggett** [comment]
I have been testing ways to do this. Once I decide how I want to do it, I'll add it to the program.

**Comment by JBSoft** [comment]
I have done that on an app made with AutoIt. I used a DropBox hosting for my projet, but I think it would be very possible to use GitHub directly. I maybe can send you pieces of my code if you want. I remember having found some examples on AutoIt forums also.
This asuming that SimpleIPConfig is still made with AutoIt ?

**Comment by KurtisLiggett** [comment]
I'd love to take a look at your example. You can post the code here or send a link to the file.
Or you could even fork the repo and add it yourself if you really wanted.

**Comment by giacomocerquone** [comment]
This should be very simple. Here an example: http://www.d3scene.com/forum/development/46425-autoit-how-write-updater.html

And to get the right url, we could use the github's api to retrieve the last release of a project. See: https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Comment by giacomocerquone** [comment]
Last doubt is to use or not to use that code section kurtis wrote to automatically update the new exe downloaded

**Comment by KurtisLiggett** [comment]
This feature is added. For further discussion, open a new issue.
