### ISSUE TITLE
[BUG] Sort Crashes and Deletes Profiles

### ISSUE THREAD

**Issue by HansieNL** [KurtisLiggett/Simple-IP-Config#150]
**Version:**
2.9.4 portable

**Expected Behavior:**
Trfying to sort profiles

**Actual Behavior:**
List is sorted but I get the following warnings:

**COM Error**
Simple IP Config COM error
Error Number: 80020003
Kan lid niet vinden.

**COM Error**
Simple IP Config COM error
Error Number: 000000A9
Variable is not of type 'Object'.

After reloading app only a default profile.ini is loaded. Looks like the old profile has disappeared?

**Comment by KurtisLiggett** [comment]
Thank you for reporting this! I will get this fixed ASAP, since it has such a critical side effect. I apologize if you lost a lot of profiles.
