### ISSUE TITLE
[CR] Save profiles in portable directory

### ISSUE THREAD

**Issue by Testato** [KurtisLiggett/Simple-IP-Config#157]
the collection of profiles is the most important thing that one creates slowly over time.
But it is not stored within the Portable directory.

I think it is a good idea to save the profiles.ini file in the portable directory so that saving the directory automatically saves the profiles.

**Comment by KurtisLiggett** [comment]
Mistake on my part. For now, if you copy the ini file to your portable directory, the program will use that file.
I can try to auto detect this in the future.

**Comment by Testato** [comment]
the simplest way is put an empty profiles.ini inside the portable .zip that you made for download ?

**Comment by KurtisLiggett** [comment]
`the simplest way is put an empty profiles.ini inside the portable .zip that you made for download ?`

That is what I had intended to do, but my release process is not exactly streamlined. I just forgot to add it to the zip. I updated the files in the 2.9.6.1 release as you suggested.

In v2.9.7 the program will auto-detect if running from the installation directory or a portable location.

**Comment by KurtisLiggett** [comment]
Now available with release v2.9.7 - [Download Here](https://github.com/KurtisLiggett/Simple-IP-Config/releases/tag/2.9.7)
