### ISSUE TITLE
System tray

### ISSUE THREAD

**Issue by Testato** [KurtisLiggett/Simple-IP-Config#159]
what is the difference between Startup in system tray and minimize to system try ?

It seems have the same behavior.
If I click the X the app will close in the same time on the two option

**Comment by KurtisLiggett** [comment]
Minimize to the system tray:
When you click the minimize button in the title bar, instead of minimizing to the taskbar like normal, the app is sent to the tray.

Startup in system tray:
When you open the program, it will start minimized to the tray.

The X button will always close the app.

**Comment by Testato** [comment]
Thanks
