### ISSUE TITLE
[BUG] Can't Download Portable

### ISSUE THREAD

**Issue by scramjetx** [KurtisLiggett/Simple-IP-Config#161]
**Version:**
What version are you using? 
2.9.6.1

**Expected Behavior:**
Browser will download the portable version

**Actual Behavior:**
I tried chrome, edge and firefox and none of them will download the file.  I think it's tripping the anti-virus still for some reason.

**Comment by KurtisLiggett** [comment]
I cannot reproduce with any browser on my PC.

**Comment by scramjetx** [comment]
I tried again just now on chrome and it worked.  Probably something with the virus software changed on my side.
