### ISSUE TITLE
[BUG]  Error reading language file

### ISSUE THREAD

**Issue by DomSaunders73** [KurtisLiggett/Simple-IP-Config#169]
**Version:**
2.9.6.1

After upgrade from 2.6.x AND on a clean install, error popup message displays on launch stating: "Error reading language file" with OK\Cancel button as per screenshot.

![image](https://user-images.githubusercontent.com/113581757/190334522-f65967cd-8cbe-46d4-b3ef-26506110e97a.png)

**Comment by blackcrack** [comment]
Hi,
@DomSaunders73 which language do you use in your OS ?

best

**Comment by DomSaunders73** [comment]
Hi,
Windows 10 and Windows11, both in English.
Thanks.

**Comment by blackcrack** [comment]
Hi @DomSaunders73 
well, did you download the latest Release ?
https://github.com/KurtisLiggett/Simple-IP-Config/releases
klick on the "Assets 3" and download the
Simple.IP.Config.2.9.7-beta1.zip
decompress and test it ..
should work .. 
best

**Comment by JonnyTech** [comment]
I assume that you downloaded the portable version, in which case extract **ALL** files and folders from the archive, not just the exe.

**Comment by DomSaunders73** [comment]
I've found the issue - my profile.ini had "language=en-GB" (note en-GB is the correct loacale not en-UK as above) in it - both the old version that upgraded and on a clean install.  There is no en-GB language pack.

Open the profile.ini and change it to en-US and it works without the error message.

Can I suggest that if it can't find a language match, there is a default fallback language pack used?

**Comment by blackcrack** [comment]
but you can make a GB language pack.. therewith, the same as en-GB .. and you have a Great Big Language pack ;)

**Comment by KurtisLiggett** [comment]
@DomSaunders73 
I will look into this. I don't remember auto-generating the language (such as en-GB). I also thought if no file was found, it would fall back to English. But it has been a while since I have had my head deep in the code, so anything is possible.

**Comment by KurtisLiggett** [comment]
I found the issue. Yes, it was reading the local language and storing it in the profiles.ini file. I changed it to only store the language when manually selecting through the settings screen.

**Comment by KurtisLiggett** [comment]
Now available with release v2.9.7 - [Download Here](https://github.com/KurtisLiggett/Simple-IP-Config/releases/tag/2.9.7)

**Comment by Leandro4002** [comment]
Hello, the problem is still not fix for me, I used the latest release.
To fix it, I had to manually go to D:\Users\username\AppData\Local\Simple IP Config\profiles.ini
and change "Language=" to "Language=en-US"

**Comment by lsymy** [comment]
Just click "Save" again in the settings, then restart app.
It's works for me.
