### ISSUE TITLE
Dutch language translation

### ISSUE THREAD

**Issue by Svantie** [KurtisLiggett/Simple-IP-Config#172]
Hi,

I translated the language file to dutch for me and my co-workers. I would love to share the translation to the project.
How can i get it added to the project if the language file is approved?

**Comment by blackcrack** [comment]
if you not directly familiarly with make a patch and make a pull
make a zip and put it via plug and pray with the mouse in the answering textfild..
and it want be uploaded .. (falls Du deutsch kannst, füge einfach das zip hier in das antwortstextfeld mit der maus ein das javascript läd es dann hoch und baut es dann als attachement in das textfeld ein)

best

**Comment by Svantie** [comment]
Cool, tnx. I totally wasn't looking at the "add file" possibility. I know the pull feature,, but anyways: [dutch_lng.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/9753005/dutch_lng.zip)

Tnx for the headsup

**Comment by blackcrack** [comment]
@KurtisLiggett a new Dutch langfile :))))

**Comment by KurtisLiggett** [comment]
I just noticed the pull request related to this.
#173 and #176 have been merged, so I am closing this issue.
