### ISSUE TITLE
[BUG] Error: line 4 array has incorrect number of subscripts or subscript dimension

### ISSUE THREAD

**Issue by Kun89896555** [KurtisLiggett/Simple-IP-Config#180]
How to fix 
![666666677](https://user-images.githubusercontent.com/126314459/221343383-e497a2f2-7e3d-481a-96a4-b68a165b714d.jpg)

**Comment by KurtisLiggett** [comment]
Could you describe what action you were trying to do when this happened?
Looking at the error, it looks like it was generated by a different application (autoclicker-1-0-0-2.exe).

**Comment by KurtisLiggett** [comment]
Closing as this seems like an issue with a different application. Re-open if needed.
