### ISSUE TITLE
IP address fields only allow 2 digits for some users

### ISSUE THREAD

**Issue by KurtisLiggett** [KurtisLiggett/Simple-IP-Config#2]
Some users are only allowed to type 2 digits into the IP address fields.
This is a DPI scaling issue.

**Comment by snappysnappydog** [comment]
Confirmed by multiple users.

**Comment by bghite** [comment]
The change in 2.8.1.b1 resolved the issue for me. 
Thank you for all of your hard work.

**Comment by KurtisLiggett** [comment]
Fix confirmed.
Marking as closed.
