### ISSUE TITLE
Error: Array Variable number of subscripts

### ISSUE THREAD

**Issue by KurtisLiggett** [KurtisLiggett/Simple-IP-Config#21]
_Issue migrated from [Sourceforge](https://sourceforge.net/p/simpleipconfig/discussion/bugreports/thread/a524721b/?limit=25)_

Some users have reported the following error.
"Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded"

![image](https://user-images.githubusercontent.com/29669372/29136003-857b11ae-7d01-11e7-923e-e5342e363eac.png)

**Comment by zingyyellow** [comment]
Hi  I'm a field engineer this app would suit me and my fellow engineers perfectly. But we're getting this same error on start up.is there a work around? Or are previous versions worth a try.
Thanks

**Comment by zapy85** [comment]
Try the beta version 2.9 beta 2 https://github.com/KurtisLiggett/Simple-IP-Config

**Comment by KurtisLiggett** [comment]
Can you please post a screenshot like the one above? It will help to find exactly where the issue is.

**Comment by zingyyellow** [comment]
Thanks I'll try that.

Hywel
