### ISSUE TITLE
Save/rearrange odd behavior

### ISSUE THREAD

**Issue by KurtisLiggett** [KurtisLiggett/Simple-IP-Config#3]
Sometimes strange things happen when rearranging profiles.
Considering rewriting the code for this.

**Comment by giacomocerquone** [comment]
Let's try to explicate better the problem, provide a use case that can replicate the problem or at least let's mark the code that is not working as it should

**Comment by KurtisLiggett** [comment]
There are several cases that I see randomly. I will describe them here as I find them.

Working with these profiles:
```
[One]
IpAuto=true
IpAddress=192.168.1.1
IpSubnet=255.255.255.0
IpGateway=
DnsAuto=true
IpDnsPref=
IpDnsAlt=
RegisterDns=false
AdapterName=Local Area Connection

[Two]
IpAuto=false
IpAddress=192.168.1.2
IpSubnet=255.255.255.0
IpGateway=
DnsAuto=false
IpDnsPref=
IpDnsAlt=
RegisterDns=false
AdapterName=Local Area Connection

[Three]
IpAuto=false
IpAddress=192.168.1.3
IpSubnet=255.255.255.0
IpGateway=
DnsAuto=false
IpDnsPref=
IpDnsAlt=
RegisterDns=false
AdapterName=Local Area Connection
```

**Case 1**
When you drag a profile to a new position (ex: drag One to Two), the order changes correctly, but you can no longer read the properties of the profile that was dragged. This will happen to each profile that is dragged and persists until the program is restarted.

The INI file seems to be updating correctly and is not getting corrupted which leads me to think it is the tracking of the internal profile arrays.

I am waiting to investigate until I finish my 'Code-Cleanup' changes because I have completely overhauled the profile tracking which should hopefully make this much easier to troubleshoot.

**Comment by giacomocerquone** [comment]
Ok, I would stop right now implementing new features (the last one would be the links stuff) in order to begin a refactoring of the whole project.
I saw you created a code-cleanup branch, but it's already behind master and merging now could get messy. So stop pushing to master and let's work there :)

**Comment by KurtisLiggett** [comment]
I understand, but I've been keeping my branch up to date with master locally and resolving conflicts as they come up so it's not too bad.

**Comment by egrosm** [comment]
I'm also experience an configuration read out issue. Maybe not completely related to the profile moving problem?

If I close the program, add the above given profile configuration and start the program again it seems that the last profile (aka Three) isn't read completely form the profile configuration file. See attached screenshot.

**[One]
IpAuto=true
IpAddress=192.168.1.1
IpSubnet=255.255.255.0
IpGateway=
DnsAuto=true
IpDnsPref=
IpDnsAlt=
RegisterDns=false
AdapterName=Local Area Connection

[Two]
IpAuto=false
IpAddress=192.168.1.2
IpSubnet=255.255.255.0
IpGateway=
DnsAuto=false
IpDnsPref=
IpDnsAlt=
RegisterDns=false
AdapterName=Local Area Connection

[Three]
IpAuto=false
IpAddress=192.168.1.3
IpSubnet=255.255.255.0
IpGateway=
DnsAuto=false
IpDnsPref=
IpDnsAlt=
RegisterDns=false
AdapterName=Local Area Connection**

![profile_three_empty](https://user-images.githubusercontent.com/30493475/28662597-fd733dd6-72ba-11e7-8b75-ef794a216932.png)

Maybe this gives you some more information to fix the issue.

**Comment by giacomocerquone** [comment]
Sorry, while this could be a bug in the code, it doesn't mean that the use you do of this programs is legit.
If I understood correctly you hack on the profiles.ini adding manually a profile... this isn't a thing you should do, but we'll investigate in this.

**Comment by egrosm** [comment]
I'm just trying to assist you to find the issue.... I found the issue during normal adding of four profiles using the add + save buttons, so it isn't "HACKING" related :-)

**Comment by giacomocerquone** [comment]
Sorry then... quoting you:

> If I close the program, add the above given profile configuration and start the program again 

I understood you were doing it manually because you add the profline when you closed the program. Good to know then

**Comment by KurtisLiggett** [comment]
@egrosm, are you using the latest release form [here](https://github.com/KurtisLiggett/Simple-IP-Config/releases/tag/2.8.1)?
Also, is that your entire profiles.ini file?

I can't reproduce the problem on my computer using the configuration you provided. My last profile always works no matter if I add it from the interface or manually editing the file.

When you open the program and try to click on the last profile, does it give any error in the status bar?

**Comment by KurtisLiggett** [comment]
As a side note, one of the reasons I use the simple INI file is so anyone can easily make edits or add profiles rapidly using copy/paste. I consider it a feature!

**Comment by egrosm** [comment]
I used 2.8.1. for testing with the profiles.

Today I let the program create an new profile and I added again the profiles (by hand). I noticed that the [options] part is at the start of the ini file. So (for testing) I moved it to the bottom of the ini file and the issue with the last profile entry was present again.

Original:
![original_order](https://user-images.githubusercontent.com/30493475/28765458-1b2e0e60-75cb-11e7-9ba5-7c36bd33e229.png)

[Options] to bottom of ini:
![reversed_order](https://user-images.githubusercontent.com/30493475/28765471-2d8ec6e4-75cb-11e7-91c9-74d4df6d207f.png)

Maybe this is something you are able to reproduce.

**Comment by KurtisLiggett** [comment]
I finally found the bug! And it is an easy fix, so I'll take care of that shortly.
Thanks for the clarification and screenshots to help track this one down.

**Comment by KurtisLiggett** [comment]
> When you drag a profile to a new position (ex: drag One to Two), the order changes correctly, but you can no longer read the properties of the profile that was dragged. This will happen to each profile that is dragged and persists until the program is restarted.

I also found this bug and  have a fix for it as well.
