### ISSUE TITLE
Hiding multiple adapters quickly

### ISSUE THREAD

**Issue by elmorekevin** [KurtisLiggett/Simple-IP-Config#36]
Might there be an easier way to hide multiple network adapters at once? It'd be a small improvement, but it would really help first time users set up the available adapters easily.

**Comment by KurtisLiggett** [comment]
Maybe list all the adapters with checkboxes next to each one?

**Comment by elmorekevin** [comment]
That should fit the bill nicely. Thanks!

**Comment by stevenolsen** [comment]
To add to this. Is there a way to exclude all dial-up adapters from being included? I remote into sites and a separate adapter is created for every single dial-up connection. When I started the app for the first time I had to remove about 60 adapters and will have to continue removing each adapter when I add another dial-up connection.
