### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by lifekiller** [KurtisLiggett/Simple-IP-Config#38]
The default adapter name in windows is 本地连接(chinese language). The program can show it correctly, but can not apply profile to the adapter. After changing the name of the adapter to english, it works fine.
Can fix this problem?

**Comment by KurtisLiggett** [comment]
Are you using an English version of Windows?

If I rename my adapter by copying/pasting your text 本地连接, it still lets me set the adapter just fine.
There are still other issues. The adapter is saved as ??? in the INI file. This is most likely an encoding issue of some sort. I will look into it, but not sure how to proceed.

**Comment by KurtisLiggett** [comment]
No response in a while.
