### ISSUE TITLE
Esc key shouldn't exit the application

### ISSUE THREAD

**Issue by Otiel** [KurtisLiggett/Simple-IP-Config#43]
It seems a little harsh to exit the application when hitting the Esc key. Alt+F4 should be the shortcut to exit the application, while Esc could be the shortcut to send the application to tray.

**Comment by KurtisLiggett** [comment]
Thanks.

To be fixed in the next version.

**Comment by KurtisLiggett** [comment]
Added this feature and will be included in the next release.
