### ISSUE TITLE
DNS Suffix needed

### ISSUE THREAD

**Issue by tf1-niceguy** [KurtisLiggett/Simple-IP-Config#61]
Besides the 2 DNS addresses I'd like to have the program save/add two DNS suffix to easily identify where my subnet belongs to. Windows DNS tab is under: "Advanced TCP/Ip config"  "Add DNS suffix in the following order". 
Eventually is better to have an option to undo suffixes to windows default: "Add DNS suffixes specifically by connection"
THKs!

**Comment by KurtisLiggett** [comment]
This would be a logical continuation of the multiple IP addresses feature proposed in #8.

**Comment by KurtisLiggett** [comment]
Closing due to reason above. Multiple IPs, gateways, DNS is not in discussions.
