### ISSUE TITLE
Windows Defender alert

### ISSUE THREAD

**Issue by bghite** [KurtisLiggett/Simple-IP-Config#62]
Hello Kurtis,

I suspect it is a false positive but thought you should know that Windows Defender is flagging 2.9.b3 as infected.

Windows Defender Event Entry:

Windows Defender Antivirus has detected malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Fuerboos.B!cl&threatid=2147723653&enterprise=0
 	Name: Trojan:Win32/Fuerboos.B!cl
 	ID: 2147723653
 	Severity: Severe
 	Category: Trojan
 	Path: file:_d:\Downloads\Simple.IP.Config.2.9.b3.exe;webfile:_d:\Downloads\Simple.IP.Config.2.9.b3.exe|https://github-production-release-asset-2e65be.s3.amazonaws.com/95271918/c6826f9c-118c-11e8-9232-c76dbae9a8f1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A4.12.17007.18011F201802194.12.17007.18011Fus-east-14.12.17007.18011Fs34.12.17007.18011Faws4_request&X-Amz-Date=20180219T223321Z&X-Amz-Expires=300&X-Amz-Signature=03a69ad949b7f8c6ede442304de69a3a98ce3f65b631f93c74ad596ddeee4f94&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition=attachment{B2AEF91A-3DBD-4D5F-9FB4-1554BEA96686}BMYPLC\bhitefilename{B2AEF91A-3DBD-4D5F-9FB4-1554BEA96686}DSimple.IP.Config.2.9.b3.exe&response-content-type=application4.12.17007.18011Foctet-stream|chrome.exe
 	Detection Origin: Internet
 	Detection Type: FastPath
 	Detection Source: Downloads and attachments
 	User: MYPLC\bhite
 	Process Name: Unknown
 	Signature Version: AV: 1.261.1353.0, AS: 1.261.1353.0, NIS: 118.2.0.0
 	Engine Version: AM: 1.1.14500.5, NIS: 2.1.14202.0

**Comment by KurtisLiggett** [comment]
Thanks for reporting this.

I assure you, this is a false positive that comes up from time to time. I'll see what I can do to fix it.

**Comment by KurtisLiggett** [comment]
I am wondering if anyone has had this issue with the final 2.9 version.

**Comment by Bocmac** [comment]
I tried to install the latest 2.9.3 today but Webroot Secure anywhere zapped the files. I tried both the setup and the exe . Our IT has the interface locked down so I can only output a log file and the only details are W32.Malware.Gen.

**Comment by JeroenVanHoye** [comment]
Hi Kurtis,
I also hope this is a false positive, because i'd hate to lose this tool.
Cisco Secure Endpoint has quarantined Simple IP Config with te following description:
> Malicious activity detected (C:\Program Files (x86)\Simple IP Config\Simple IP Config.exe)[W32.Trojan.26fn.1201].

The version of the tool I had installed is 2.9.7 on a W11 (23H2) with Secure client version 8.2.3.30119.
Could you check on this so I can whitelist this tool?
