### ISSUE TITLE
Select Adapter panel should be an IN/OUT field

### ISSUE THREAD

**Issue by egrosm** [KurtisLiggett/Simple-IP-Config#67]
Hello,

I have an issue / feature request. 

There are currently 2 method's to apply an profile: With de Apply button and with an shortcut. When using the apply button, the adapter selected in the "Select adapter" panel is used for the profile. The shortcut methode reads the configured adapter from the configuration and apply's the settings to that adapter.

![afbeelding](https://user-images.githubusercontent.com/30493475/39306926-c5b56bf2-4961-11e8-876b-455995f8c064.png)

It would be great if the Select adapter will become an Input/Output field, what will read the configured adapter (for the specific profile) when selecting a profile.

**Comment by KurtisLiggett** [comment]
As you have seen in the INI file, the program already stores the selected adapter to the profile.

**SOLUTION:**
In order to use that feature, simply _go to Tools->Settings and check the box for 'Save adapter to profile'_.

I am open to suggestions if the wording is confusing.

**Comment by zapy85** [comment]
Just add an explanation to what it does.
Like
" Saves chosen adapter in main windows select adapter to the profile you create "
