### ISSUE TITLE
Turn off auto update

### ISSUE THREAD

**Issue by NashVillainy** [KurtisLiggett/Simple-IP-Config#69]
For some reason each time the program updates I lose all of my profiles.  There is probably a way to fix this, but it might also be good to choose when to update instead of having updates automated.

I love this program by the way, great work!

**Comment by KurtisLiggett** [comment]
Do you have the checkbox unchecked for the "Enable automatic updates" setting?
I'll try to see why the profiles could have been deleted.

**Comment by NashVillainy** [comment]
Thank you.  I think this may have been all user error.  I realized today
that the profiles were saved to my desktop and I had deleted them when
cleaning up.  I am on an older version which doesn't seem to have update
options. I think I was confused by seeing the changeling after deleting
profiles.




On May 30, 2018 11:48 AM, "Kurtis Liggett" <notifications@github.com> wrote:

Do you have the checkbox unchecked for the "Enable automatic updates"
setting?
I'll try to see why the profiles could have been deleted.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KurtisLiggett/Simple-IP-Config/issues/69#issuecomment-393232922>,
or mute the thread
