### ISSUE TITLE
Feature Request - Add option to ping an address to verify connection

### ISSUE THREAD

**Issue by ChadEmory** [KurtisLiggett/Simple-IP-Config#74]
Request the addition to the tool, of pinging an address that can be entered to test the connection before/after the change. Basically the same as opening a CMD windows and doing a "ping" + a user inputed address to test.

**Comment by KurtisLiggett** [comment]
I like this idea.
I'll see how much it would take to implement.

**Comment by KurtisLiggett** [comment]
As described in the top post, only minimal effort is required to open a command prompt. Closing this request.
