### ISSUE TITLE
After using search, profiles only load last selected profile

### ISSUE THREAD

**Issue by ericberard** [KurtisLiggett/Simple-IP-Config#75]
When I perform a search to find the profile I'm looking for, I realized that I can't set the profile. Upon further examination, I notice that from my search results, when I select a profile, none of the profile's settings change on the right hand side of the window. Even after I clear out the search and put back the "*" to get the full list of profiles again the same thing happens, selecting other profiles doesn't actually load the profiles.

In every instance that I've noticed this, it is profile that was selected previous to the search that persists.

The only way to get profiles to reload properly again is to restart the application.

EB

**Comment by ericberard** [comment]
I can confirm that this is fixed in version 2.9.2. Thanks for the promptness.

EB

**Comment by blackcrack** [comment]
@ericberard you can make a comment and you see the button "comment and close",
this can you use to close this Issue :) thank you :bowtie:
:thumbsup:

**Comment by ericberard** [comment]
Issue resolved.
