### ISSUE TITLE
Load/Grab current Configuration

### ISSUE THREAD

**Issue by blackcrack** [KurtisLiggett/Simple-IP-Config#81]
Hi,

Button : "Load/Grab" Configuration,  "Load from Mashin Configuration + Save current Configuration" + add Mashin+domain-name as 
Profilname (a.E.:blackysgate2.de)

maybe also strg/crtl + m as hotkey for load ip's/configuration in the textfilds and save as profile
so strg/crtl + &Mashin for saving current mashin as profile and display.

**Comment by KurtisLiggett** [comment]
I think what you are looking for is in the tools menu under Pull from adapter or keyboard shortcut Ctrl+p.

**Comment by blackcrack** [comment]
yepp, could may good if the buttonbar customable with different buttons :)
but this issue is close so far...
pull from adapter/ "load from adapter" maybe

thank you for help :)
