### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [KurtisLiggett/Simple-IP-Config#84]
@KurtisLiggett 

Could you please enable multi-language in future release?
If you can please external language text file to enable very easy changes to the interface.

Thanks.

**Comment by KurtisLiggett** [comment]
We can do that. I'll put it on the list.

**Comment by blackcrack** [comment]
if it exist, can the peoples help to translate the program to be international, 
so you must easy integrate the language selector and your Program 
is like a Honeypot for translater ;)

**Comment by KurtisLiggett** [comment]
I'm sure we'll find more later, but let's start with this.
- Translate the text on the right side of the equals sign ( = ).
- For menus, the & symbol indicates which keyboard key activates that menu item when using Alt+...
   - Example1:  **&File** is accessible by pressing **Alt**, then pressing **f**
   - Example2:  **Send to &tray** is accessible by pressing **Alt**, then pressing **t**
- Go to the [Wiki translations page](https://github.com/KurtisLiggett/Simple-IP-Config/wiki/Translations) and create a new page called 'lang__en_us' where 'en_us' would be replaced with your language code.
    - Paste your translations inside INI code tags:
          - `` ```INI [menu] file=&File ... ``` ``
    - The example below is for 'American English', so the wiki page is named 'lang__en_us'
    - If you want to be an overachiever, edit the main translations page to add your new language to the list.
- Or just be lazy and post your translation here.

```INI
[menu]
file=&File
file_apply=&Apply profile
file_rename=&Rename
file_new=&New
file_save=&Save
file_delete=&Delete
file_clear=&Clear entries
file_createShortcut=&Create s&hortcut to profile
file_exit=&Exit
view=&View
view_refresh=&Refresh
view_tray=Send to &tray
view_hideAdapters=&Hide adapters
tools=&Tools
tools_pull=&Pull from adapter
tools_disable=Dis&able adapter
tools_enable=En&able adapter
tools_release=&Release DHCP
tools_renew=Re&new DHCP
tools_renewCycle=Release/renew &cycle
tools_settings=&Settings
help=&Help
help_doc=&Online Documentation
help_changelog=Show &Change Log
help_updates=Check for &Updates...
help_debug=&Debug Information
help_about=&About Simple IP Config
[toolbar]
apply=Apply
refresh=Refresh
refresh=New
refresh=Save
refresh=Delete
refresh=Clear
apply_tip=Apply
refresh_tip=Refresh
refresh_tip=Create new profile
refresh_tip=Save profile
refresh_tip=Delete profile
refresh_tip=Clear entries
tip=Settings
tip=Send to tray
[heading]
adapter=Select Adapter
profiles=Profiles
profileProperties=Profile IP Properties
adapterProperties=Current Adapter Properties
[misc]
MAC_address=MAC Address
computerName=Computer Name
[IP]
auto=Automatically Set IP Address
man=Manually Set IP Address
address=IP Address
subnet=Subnet Mask
gateway=Gateway
[DNS]
auto=Automatically Set DNS Address
man=Manually Set DNS Address
pref=Preferred DNS Server
alt=Alternate DNS Server
register=Register Addresses
[CurrentProperties]
dhcp=DHCP Server
state=Adapter State
state_disabled=Disabled
state_enabled=Enabled
[status]
ready=Ready
timeout=Action timed out! Command Aborted.
shortcutError=Could not save to the selected location!
updateAdapters=Updating Adapter List...
applySelect=Please select an adapter and try again
enterIP=Please enter an IP address
enterSubnet=Please enter a subnet mask
settingStaticIP=Setting static IP address...
settingDhcp=Setting DHCP...
settingStaticIP=Setting static IP address...
settingDnsDhcp=Setting DNS DHCP...
settingDnsPref=Setting preferred DNS server...
settingDnsAlt=Setting alternate DNS server...
deletingDNS=Deleting DNS servers...
saveError=An error occurred while saving the profile
deleteError=An error occurred while deleting the profile
selectError=No profile is selected!
noIniFile=Profiles.ini file not found - A new file will be created
IniError=Error reading profiles.ini
profileListError=An error occurred while building the profile list
[message]
error_com=COM Error
error_number=Error Number
updates_title=Automatic Update Error
updates_desc=An error was encountered while retrieving the update.
error_adapters=There was a problem retrieving the adapters.
error_warning=Warning
error_rename=The profile name already exists
[settings]
title=Settings
startupInTray=Startup in the system tray
minToTray=Minimize to the system tray
saveAdapter=Save adapter to profile
autoUpdate=Enable automatic updates
cancel=Cancel
save=Save
[hide_adapters]
title=Adapter Blacklist
desc=Select Adapters to Hide
cancel=Adapter Blacklist
save=Adapter Blacklist
[changelog]
title=Change Log
desc=Changelog
[about]
title=About
version=Version
date=Date
developer=Developer
license=License
description=The portable ip changer utility that allows a user to quickly and easily change the most common network settings for any connection.
icons=Program icons are from
ok=OK
[update]
title=Check for Updates
yourVersion=Your Version
latestVersion=Latest Version
messageLatest=You have the latest version
messageNew=A newer version is available
messageNew_here=here
[tray]
hide=Hide
show=Restore
about=About
exit=Exit
```

**Comment by bovirus** [comment]
Italian translation added as page and copied here

[menu]
file=&File
file_apply=&Applica profilo
file_rename=&Rinomina
file_new=&Nuovo
file_save=&Salva
file_delete=E&limina
file_clear=A&zzera elementi
file_createShortcut=&Crea collegamento nel profilo
file_exit=&Esci
view=&Visualizza
view_refresh=A&ggiorna
view_tray=Minimizza nella barra di sis&tema
view_hideAdapters=&Nascondi schede di rete
tools=S&trumenti
tools_pull=&Ottieni dalla scheda di rete
tools_disable=Dis&abilita scheda di rete
tools_enable=&Abilita scheda di rete
tools_release=O&ttieni indirizzi via DHCP
tools_renew=R&innova indirizzi via DHCP
tools_renewCycle=Cicli nuovo/rinnova indirizzi via DHCP
tools_settings=&Impostazioni
help=&?
help_doc=&Guida in linea
help_changelog=Visuali&zza novità programma
help_updates=Controlla a&ggiornamenti...
help_debug=Informazioni &debug
help_about=&Informazioni sul programma

[toolbar]
apply=Applica
refresh=Aggiorna
refresh=Nuovo
refresh=Salva
refresh=Elimina
refresh=Azzera
apply_tip=Applica
refresh_tip=Aggiorna
refresh_tip=Crea nuovo profilo
refresh_tip=Salva profilo
refresh_tip=Elimina profilo
refresh_tip=Azzera impostazioni
tip=Impostazioni
tip=Minimizza nella barra di sistema

[heading]
adapter=Seleziona scheda di rete
profiles=Profili
profileProperties=Proprietà IP profilo
adapterProperties=Proprietà attuali scheda di rete

[misc]
MAC_address=Indirizzo MAC
computerName=Nome computer

[IP]
auto=Impostazione automatica indirizzo IP
man=Impostazione manuale indirizzo IP
address=Indirizzo IP
subnet=Maschera sottorete
gateway=Gateway

[DNS]
auto=Impostazione automatica indirizzo DNS
man=Impostazione manuale indirizzo DNS
pref=Server DNS primario
alt=Server DNS secondario
register=Indirizzo registrazione
[CurrentProperties]
dhcp=Server DHCP
state=Stato scheda di rete
state_disabled=Disabilitata
state_enabled=Abilitata

[status]
ready=Pronto
timeout=Timeout azione! Comando annullato.
shortcutError=Impossibile salvare nel percorso indicato!
updateAdapters=Aggiornamento elenco schede di rete...
applySelect=Seleziona una scheda di rete e riprova
enterIP=Inserisci un indirizzo IP
enterSubnet=Inserisci una maschera di sottorete
settingStaticIP=Impostazione indirizzo IP statico...
settingDhcp=Impostazione DHCP...
settingStaticIP=Impostazione indirizzo IP statico...
settingDnsDhcp=Impostazione DNS DHCP...
settingDnsPref=Impostazione server DNS primario...
settingDnsAlt=Impostazione server DNS secondario...
deletingDNS=Eliminazione server DNS...
saveError=Si è verificato un errore durante il salvataggio del profilo
deleteError=Si è verificato un errore durante l'eliminazione del profilo
selectError=Nessun profilo selezionato!
noIniFile=File Profiles.ini non trovato - verrà creato un nuovo file
IniError=Si è verificato un errore durante la lettura del file profiles.ini
profileListError=Si è verificato un errore durante la creazione dell'elenco profili

[message]
error_com=Errore COM
error_number=Codice errore
updates_title=Errore aggiornamento automatico
updates_desc=Si è verificato un errore durante durante il download dell'aggiornamento.
error_adapters=Si è verificato un errore durante il rilevamento delle schede di rete.
error_warning=Attenzione
error_rename=Questo nome profilo esiste già

[settings]
title=Impostazioni
startupInTray=Avvia ridotto nella barra di sistema
minToTray=Minimizza nella barra di sistema
saveAdapter=Salva scheda nel profilo
autoUpdate=Abilita aggiornamento automatico
cancel=Annulla
save=Salva

[hide_adapters]
title=Elenco schede di rete nascoste
desc=Seleziona schede da nascondere
cancel=Annulla
save=Salva

[changelog]
title=Novità programma
desc=Novità programma

[about]
title=Informazioni sul programma
version=Versione
date=Data
developer=Sviluppatore
license=Licenza
description=Un'utility portatile per la modifica degli indirizzi IP che permette all'utente di modificare facilmente e velocemente le impostazioni di reti più comuni per qualsiasi tipo di connessione.
icons=Icone programma realizzate da 
ok=OK

[update]
title=Controlla aggiornamenti
yourVersion=Versione installata
latestVersion=Versione disponibile
messageLatest=La versione installata è aggiornata
messageNew=È disponibile una nuova versione
messageNew_here=qui

[tray]
hide=Nascondi
show=Ripristina
about=Info sul programma
exit=Esci

**I propose you to add a new empty line to divide the section of each group of strings**

**_** Please take care about these original string_**

[menu]
file_createShortcut=**_&_**Create s**_&_**hortcut to profile -> double & & character

[hide_adapters]
cancel=**Adapter Blacklist** -> shoudl be "**Cancel**"?
save=**Adapter Blacklist** -> should be "**Save**"?

**Comment by KurtisLiggett** [comment]
@bovirus Thank you for your contributions. I edited your comment to link to the translation page so this thread doesn't get too big.

Thanks for discovering my mistakes, I have edited the English example.

**Comment by bovirus** [comment]
Thank you toe dited the file.

I propose you to change the language name in Wiki translation page in

English (US)
Italian

**Comment by blackcrack** [comment]
[menu]
file=&Datei
file_apply=Profil &anwenden
file_rename=&Umbenennen
file_new=&Neu
file_save=&Speichern
file_delete=&Löschen
file_clear=&Lösche Einträge
file_createShortcut=Verknüpfung zum Profi&l erstellen
file_exit=&Exit
view=&Ansicht
view_refresh=&Aktualisieren
view_tray=Sende zum &Tray
view_hideAdapters=&Verstecke Adapter
tools=&Werkzeuge
tools_pull=&Lese vom Netzadapter
tools_disable=&Deaktiviere Adapter
tools_enable=&Aktiviere Adapter
tools_release=&Veröffentliche DHCP
tools_renew=Er&neuere DHCP
tools_renewCycle=Freigabe/Erneuerung &Zyklus
tools_settings=&Einstellungen
help=&Hilfe
help_doc=&Online Documentation
help_changelog=&Protokoll anzeigen und ändern
help_updates=Schauer nach &Updates...
help_debug=&Debug Information
help_about=&Über Simple IP Config

[toolbar]
apply=Übernehmen
refresh=erneuern
refresh=neu
refresh=sichern
refresh=löschen
refresh=clearen
apply_tip=führe den tip aus
refresh_tip=erneuern
refresh_tip=Erstelle ein neues Profil
refresh_tip=sichere Profil
refresh_tip=lösche Profil
refresh_tip=entferne Einträge
tip=Einstellungen
tip=Sende zu Systray

[heading]
adapter=Wähle ein Adapter aus
profiles=Profile
profileProperties=Profil IP Eigenschaften
adapterProperties=Aktuelle Adapter Einstellungen

[misc]
MAC_address=MAC Addresse
computerName=Computer Name

[IP]
auto=Setze automatisch die IP Addresse
man=Manuelle IP Einstellung
address=IP Addresse
subnet=Subnetz Maske
gateway=Gateway

[DNS]
auto=Setze automatische DNS Addresse
man=Manuelle DNS Adresse
pref=Preferred DNS Server
alt=Alternate DNS Server
register=Register Addresses

[CurrentProperties]
dhcp=DHCP Server
state=Adapterstatus
state_disabled=Deaktiviert
state_enabled=Aktiviert

[status]
ready=Bereit
timeout=Aktion abgelaufen! Befehl abgebrochen.
shortcutError=Speichern am ausgewählten Ort nicht möglich!
updateAdapters=Aktualisierung der Adapter Liste...
applySelect=Bitte wählen Sie einen Adapter aus und versuchen Sie es erneut
enterIP=Bitte geben Sie eine IP-Adresse ein
enterSubnet=Bitte geben Sie eine Subnetzmaske ein
settingStaticIP=Festlegen der statischen IP-Adresse...
settingDhcp=DHCP einstellen...
settingStaticIP=Festlegen der statischen IP-Adresse...
settingDnsDhcp=DNS-DHCP einstellen...
settingDnsPref=Bevorzugte DNS-Server einstellen...
settingDnsAlt=Einstellen eines alternativen DNS-Servers...
deletingDNS=DNS-Server löschen...
saveError=Beim Speichern des Profils ist ein Fehler aufgetreten
deleteError=Beim Löschen des Profils ist ein Fehler aufgetreten
selectError=Es ist kein Profil ausgewählt!
noIniFile=Profiles.ini-Datei nicht gefunden - Eine neue Datei wird erstellt
IniError=Fehler beim Lesen von profiles.ini
profileListError=Beim Erstellen der Profilliste ist ein Fehler aufgetreten

[message]
error_com=COM Error
error_number=Fehlernummer
updates_title=Fehler beim automatischen Update
updates_desc=Beim Abrufen des Updates ist ein Fehler aufgetreten.
error_adapters=Beim Abrufen der Adapter ist ein Problem aufgetreten.
error_warning=Warnung
error_rename=Der Profilname ist bereits vorhanden !

[settings]
title=Einstellungen
startupInTray=Start in der Systemleiste
minToTray=Minimire in die Systemleiste
saveAdapter=Adapter im Profil speichern
autoUpdate=Automatische Updates aktivieren
cancel=Abruch
save=Sichern

[hide_adapters]
title=Adapter Blacklist
desc=Wählen Sie zum Ausblenden Adapter aus
cancel=Abruch
save=Sichere

[changelog]
title=Change Log
desc=Changelog

[about]
title=Über..
version=Version
date=Datum
developer=Entwickler
license=Lizenz
description=Das Portable IP-Wechsler-Dienstprogramm, mit dem Benutzer die häufigsten Netzwerkeinstellungen für jede Verbindung schnell und einfach ändern können.
icons=Program icons sind von
ok=OK

[update]
title=Auf Updates prüfen
yourVersion=Deine Version
latestVersion=letzte Version
messageLatest=Du hast die letzte Version
messageNew=Eine neuere Version ist verfügbar
messageNew_here=Hier

[tray]
hide=Verstecken
show=Herstellen
about=Über..
exit=Exit!

**Comment by KurtisLiggett** [comment]
Thanks for your help @blackcrack!

**Comment by blackcrack** [comment]
Thanks for this pretty nice Program @KurtisLiggett ;)

**Comment by bovirus** [comment]
@KurtisLiggett 

Could you please change description (for language) 

https://github.com/KurtisLiggett/Simple-IP-Config/wiki/Translations

as

English (US)
Italian
German

**Comment by blackcrack** [comment]
@bovirus & @KurtisLiggett 
you meant the US-States Lang to see to be not UK-EN so (US-EN) for this english.. like something how german de-DE (normal english) and at-DE (Austria) to set an extension in name..

**Comment by KurtisLiggett** [comment]
I'm not sure I follow.
My intent was to create a chart like the one on this page:
[Language localisation](https://en.wikipedia.org/wiki/Language_localisation)

**Comment by bovirus** [comment]
@KurtisLiggett 

I just sugegst you to use a standard name like

English (EN-US)
Italian (IT)
German (DE)

instead Standard xxx (ex. Standard Italian) that for me sound not so fine.

**Comment by KurtisLiggett** [comment]
So you are saying just drop the "standard" part.
So for Italian, you would have "Italian" and" Swiss Italian"

**Comment by bovirus** [comment]
@KurtisLiggett 

First original language name and between () the specification if is not base language

ex.

English (US)
English (UK) -> -> if it will be available
German
German (Swiss) -> if it will be available.
Italian
Italian (Swiss) -> if it will be available. Not "Swiss Italian"

I made also some example of language not available just to clarify my explanation.

**Comment by blackcrack** [comment]
Hi @bovirus ,
no, the standart is, de_DE and at_DE and so on, this should also named
like it is standard, @KurtisLiggett  have right if named like it is 
in the Internet Wiki and hold it like it is.. as standard named ..
let us not start to make a new standard, Dude ;)

**Comment by bovirus** [comment]
@blackcrack

Please take care that we are talking about language description and not about locale language definition.

If it's locale definition is

de_DE - German
it_IT -> Italian

We are takling about language description name (pelaese check column name).
and it's

German
Italian

**Comment by blackcrack** [comment]
@bovirus , stay on @KurtisLiggett  decision and accept the rules ! 
https://en.wikipedia.org/wiki/Language_localisation
Stay this way and end.. 
@KurtisLiggett i guess this tread should close \*imho*

**Comment by bovirus** [comment]
@blackcrack 

Mine is just  a proposal.
Because "Standard Italian" for an Italian is unknown term.

**Comment by blackcrack** [comment]
> 
> 
> So you are saying just drop the "standard" part.
> So for Italian, you would have "Italian" and" Swiss Italian"

:+1:

**Comment by bovirus** [comment]
@KurtisLiggett 

No.  I told about

Italian
Italian (Swiss)

**Comment by blackcrack** [comment]
Non hai una decenza, non puoi semplicemente stare zitto e basta prenderlo?
vuoi essere ostinato, allora hai torto qui!
Il progetto appartiene a Kurtis!
Do not you have a decency, can not you just shut up and just take it?
do you want to be obstinate, then you are wrong here!
The project belongs to @KurtisLiggett !
He decides / lui può decidere !

@KurtisLiggett is maybe better to close this tread 
and you decide how you it want.

**Comment by bovirus** [comment]
@blackcrack 

Era una risposta a quello che hai affermato tu,
Prima di aprire bocca impara cos'è l'educazione e il rispetto verso gli altri!
E non hai nessun diritto di dire agli altri cosa devono fare,.
La mamma dei cretini è sempre incinta!

It was an answer to what you said,
Before opening your mouth, learn what education is and respect for others!
And you have no right to tell others what to do,.
The jerks' mother is always pregnant!

**Comment by blackcrack** [comment]
> 
> 
> @blackcrack
> 
> Era una risposta a quello che hai affermato tu,
> Prima di aprire bocca impara cos'è l'educazione e il rispetto verso gli altri!
> E non hai nessun diritto di dire agli altri cosa devono fare,
> E magari potrebbe esssere utile imparare la lingua italiana e inglese.
> Solo un non italiano madrelingua userebbe "Swiss Italian".
> 
> It was an answer to what you said,
> Before opening your mouth, learn what education and respect vs others people!
> You have no right to tell others what to do,.
> And maybe could be useful to learn the Italian and English language.
> Only a non-native Italian speaker would use "Swiss Italian".

tztztz ...

**Comment by KurtisLiggett** [comment]
This is getting out of hand..
Can we all try to respect each other and try to see the other person's point of view?
Closing due to _**nonconstructive**_.
