### ISSUE TITLE
Use of multi-language UI

### ISSUE THREAD

**Issue by bovirus** [KurtisLiggett/Simple-IP-Config#86]
@KurtisLiggett 

How Is it possible to configure Simple IP Config to use the translations available (like Italian)?

How to do that? Thanks.

**Comment by blackcrack** [comment]
https://github.com/KurtisLiggett/Simple-IP-Config/issues/84
close please this discussion is done

**Comment by bovirus** [comment]
Sorry but I didn't find/see instruction how to configure Simple IP Confi to see the program with Italian language.

Thanks.

**Comment by KurtisLiggett** [comment]
This feature is still being worked on, so there is not currently an option for other languages.

**Comment by KurtisLiggett** [comment]
Discussion #110 has been created to continue the discussion. Closing this issue.

**Comment by bovirus** [comment]
@KurtisLiggett 

The link 110 point to a discussion "Multiple IP Addresses per Profile".

I bleieve that there is no relation to multi language GUI.

**Comment by KurtisLiggett** [comment]
Sorry, #117  Multiple Language Support.
