### ISSUE TITLE
Installer - Enable multi language option

### ISSUE THREAD

**Issue by bovirus** [KurtisLiggett/Simple-IP-Config#87]
@KurtisLiggett 

I have a proposal to enable multilanguage installer based on Inno Setu.

If you change the Inno Setup installer script in this way

[CustomMessages]
default.AppName=Simple IP Config
default.LaunchProgram=Start Simple IP Config after finishing installation
italian.AppName=Simple IP Config
italian.LaunchProgram=Avvia Simple IP Config ad installazione completata

[Languages]
Name: "default"; MessagesFile: "compiler:default.isl"; 
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"; 

You can have English and Italian language (and in the same way add other languages).

**Comment by KurtisLiggett** [comment]
Thanks for this.
I'll test it out when I get the languages added.

**Comment by KurtisLiggett** [comment]
Started discussion #117 to further discuss this functionality.
