### ISSUE TITLE
[new feature] password protection

### ISSUE THREAD

**Issue by webmathieu** [KurtisLiggett/Simple-IP-Config#88]
Could it be possible to password protect any change on profiles? (usefull in case of using the software by a shared computer)

**Comment by blackcrack** [comment]
for what do you it need ?
because in the Administrations it is possible to blacklisting a program and for the the "normal user" cant it be start, so it is unnecessary to setting up password in each profile ..
Explain why this should be in it  and i tell you if it be worth or not ..
maybe can you it yourself explain, why not.. so can you close this 
by self with the next post if you want .. ;)

**Comment by webmathieu** [comment]
it is about using the program on a shared computer, i would like other user to be abble to activate a profile, and let them choose on witch card (3 differents card are installed) they want to activate this profile, but i don't want they could change the ip adresses . i will create all needed profiles, and they can only select the card and activate an existing profiles . 
PS: ishortcut tool:
i  try to use shortcut tool, but then i have to multiplies the profiles for each card i have, also it's not working on some computer, whereas the windows indicates modification was applied successfully, but it's always working if i m applying profiles directky with the program, and by this way i can check easly after then current card configuration

**Comment by Benik3** [comment]
Does all users use one windows profile or they have each own?
Because otherwise there could be way to just protect the .ini files with profiles from writing by these users...

**Comment by blackcrack** [comment]
there is also the possible to protect the exe file with a upx packer and a password.. this is also possible
with a execrypt where make the binary password protected .. 

best
Blacky

**Comment by KurtisLiggett** [comment]
I will not be adding any password features any time soon. Others are welcome to try and we can discuss adding them in.
