### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zvonko44** [KurtisLiggett/Simple-IP-Config#89]
**Version:**
2.9.3

**Expected Behavior:**
It should run without any issue

**Actual Behavior:**
When I run the application, my McAfee antivirus recognizes it as a Trojan end deletes the .exe file. I tried to run it inside some virtual container on the same machine but still McAfee intercepts all my attempts and deletes the .exe. The only description from McAfee console is: 
------------------------------------------------------------------------------------
Detection Name: TIE/Suspect!084AA3E661B5
Type: Trojan
Number of objects: 4
AMCore Content Version: 3756.0
Rescan status: Clean
Files: <path>\simpleipconfig.exe --> I renamed it to this name
Registry Values: System\CurrentControlSet\Control\SafeBoot\AlternateShell
                         S-1-5-....\Software\Microsoft\Internet Explorer\Main\Start Page
------------------------------------------------------------------------------------

Regards.

**Comment by controlzone** [comment]
I have had similar issues with Cylance. I have had to ask our central IT to whitelist it but it was only for a specific version. Now I try to update it, Cylance quarantines it again. 
IT have advised they require a digital certificate and the application signed.

**Comment by KurtisLiggett** [comment]
This happens from time to time and usually clears up on its own. I can try to submit a false positive report to these AV companies.
