### ISSUE TITLE
Register Addresses (DNS)

### ISSUE THREAD

**Issue by JonnyTech** [KurtisLiggett/Simple-IP-Config#90]
Can you please explain exactly what the `Register Addresses` checkbox in the DNS section does and why we should (or should not) use it?

**Comment by KurtisLiggett** [comment]
This checkbox is for the functionality of the "Register this connection's addresses in DNS" checkbox in the DNS tab of the advanced TCP/IP settings in Windows, like below:
![image](https://user-images.githubusercontent.com/29669372/63310766-91acac00-c2c1-11e9-9daf-ffad6d6a3f23.png)

--
Here is a description from Microsoft, taken from [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754143(v=ws.11)):

**Register this connection's addresses in DNS** specifies that the computer attempt dynamic registration of the IP addresses (through DNS) of this connection with the full computer name of this computer, as specified on the **Computer Name** tab (available in System in Control Panel). The local setting is used only if the associated Group Policy is disabled or unspecified.

**Comment by JonnyTech** [comment]
Perfect, thanks for the info @KurtisLiggett
