### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [KurtisLiggett/Simple-IP-Config#94]
Hello, thanks for the GNU GPL version 3 program! Added a program to a Russian-language site about free software ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/simple-ip-config.html)).

Are there any plans to add more languages? ready to help with translation into Russian.

**Comment by KurtisLiggett** [comment]
Language support will be discussed in the new discussion #117 .
