### ISSUE TITLE
COM Error! Error Number: 80020009

### ISSUE THREAD

**Issue by MrBeavers1** [KurtisLiggett/Simple-IP-Config#96]
Really love this app! I work on many different networks and this will help a lot.

I just installed v.2.9.3 and am now getting this error upon initial launch of the app. Please see pic attached.
One note is that the app does launch to a private network, sometimes with & without internet access...

![Com Error-80020009](https://user-images.githubusercontent.com/78175492/106193640-c6da5080-617b-11eb-8395-d4811293f41e.JPG)

**Comment by KurtisLiggett** [comment]
I believe this is related to checking to updates with no internet connection.
Bug should be fixed and will be included in the next release.
