### ISSUE TITLE
[BUG] COM Error! Error Number: 80020009

### ISSUE THREAD

**Issue by MrBeavers1** [KurtisLiggett/Simple-IP-Config#97]
**Version:**
What version are you using?
2.9.3

**Expected Behavior:**
A clear description of what you expected to happen.
A Clean Launch of the app

**Actual Behavior:**
A clear description of what _actually_ happened.
I receive a popup window with the following error, (see attached pic)...
COM Error! Error Number: 80020009

![Com Error-80020009](https://user-images.githubusercontent.com/78175492/106194815-503e5280-617d-11eb-8d9e-04990e160f52.JPG)

**Comment by KurtisLiggett** [comment]
I believe this is related to checking to updates with no internet connection.
Bug should be fixed and will be included in the next release.
