### ISSUE TITLE
[Suggestion] Add ability to save all profiles to easily transfer to new computer. 

### ISSUE THREAD

**Issue by Mulyut** [KurtisLiggett/Simple-IP-Config#99]
Would make life much easier if you get a new PC or setup a new tech with all profiles needed. 

If I understand correctly the current profiles only work on the computer they were made on?

**Comment by KurtisLiggett** [comment]
The profiles.ini file can be copied from the install folder C:\Program Files (x86)\Simple IP Config then restored to the new PC.
Perhaps there should be a feature to export/import the profiles to/from a user selected location.

If you are using the portable version, the profiles.ini file should be in a same directory as the main program exe.

**Comment by KurtisLiggett** [comment]
Added feature and will be included in the next release.

**Comment by Mulyut** [comment]
Awesome sounds great! I use this every day so I'm pretty stoked.
